-- Sprint F-2: seed the series table (55 distinct series from BLGRPMasterMetadatav2.csv)
-- Two CSV spelling-variant pairs were canonicalised to a single series each:
--   'Twice-Dead King' + 'The Twice Dead King'      -> 'The Twice-Dead King'
--   'Jarnhamar Pack'  + 'Space Wolves: Jarnhamar'  -> 'Jarnhamar'
-- The alias spellings are mapped onto these canonical ids in the F-3 junction seed.
-- ON CONFLICT (name) DO NOTHING makes this idempotent.

INSERT INTO public.series (name) VALUES
  ('Adeptus Mechanicus (Sanders)'),
  ('Ahriman'),
  ('Belisarius Cawl Trilogy'),
  ('Bequin'),
  ('Black Legion'),
  ('Blood Angels (Haley)'),
  ('Carcharodons'),
  ('Ciaphas Cain'),
  ('Dark Coil'),
  ('Dark Imperium'),
  ('Dawn of Fire'),
  ('Deathwatch'),
  ('Eisenhorn'),
  ('Fabius Bile'),
  ('Farsight'),
  ('Forges of Mars'),
  ('Gaunt''s Ghosts'),
  ('Grey Knights'),
  ('Horusian Wars'),
  ('Imperial Knights (Clark)'),
  ('Iron Hands (Flesh Is Weak)'),
  ('Iron Warriors'),
  ('Jarnhamar'),
  ('Last Chancers'),
  ('Legacy of Caliban'),
  ('Mephiston'),
  ('Minka Lesk'),
  ('Night Lords'),
  ('Overfiend of Octarius'),
  ('Path of the Dark Eldar'),
  ('Path of the Eldar'),
  ('Phantine/Sabbat Air War'),
  ('Phoenix Lords'),
  ('Ragnar Blackmane'),
  ('Ravenor'),
  ('Renegades'),
  ('Rise of the Ynnari'),
  ('Saint Archive'),
  ('Shira Calpurnia'),
  ('Sister Augusta'),
  ('Sisters of Battle (Swallow)'),
  ('Soul Drinkers'),
  ('Space Marine Battles'),
  ('Space Marine Conquests'),
  ('Space Marine Legends'),
  ('Space Wolf (William King)'),
  ('The Twice-Dead King'),
  ('Tome of Fire'),
  ('Ufthak Blackhawk'),
  ('Uriel Ventris'),
  ('Vaults of Terra'),
  ('War for Armageddon'),
  ('Warhammer Crime'),
  ('Watchers of the Throne'),
  ('Word Bearers')
ON CONFLICT (name) DO NOTHING;
